[build]
  publish = "."

[[redirects]]
  from = "/criar-loja"
  to = "/criar-loja.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
